name: Random Cron
on:
    workflow_dispatch:

jobs:
    repo-sync:
        runs-on: ubuntu-latest
        timeout-minutes: 3
        steps:
            - uses: actions/checkout@v5
              with:
                  token: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：README
            - name: random cron
              run: |
                  source cron_convert.sh
                  echo "configed CRON_HOURS ${{ vars.CRON_HOURS }}"
                  persist_execute_log ${{ github.event_name }} ${{ vars.CRON_HOURS }}
                  git config user.name github-actions
                  git config user.email github-actions@users.noreply.github.com
                  git add .
                  current=`TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S'`
                  git commit -m "[${current}] update cron hours by ${{ github.event_name }}"
                  git push origin master
